home/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path,re_path
from . import views
from django.contrib.auth import views as auth_views
from rest_framework import routers
from rest_framework.urlpatterns import format_suffix_patterns

app_name="home"

urlpatterns = [
    path("",views.index,name="home-page"),
    path("search/",views.food_search_view.as_view(),name="search_food"),
    # path("info/<slug:urll>",views.allinfo,name="recipe"),
    path("register/",views.register,name="register-user"),
    path("profile/",views.profile,name="profile"),
    re_path(r'info/(?P<urll>[a-zA-Z0-9_#:./]+)$',views.allinfo,name="recipe"),#FDFUFUFUFUCKCKKC YESS
    
    path("login/",auth_views.LoginView.as_view(template_name="home/login.html"),name="login"),

    path("logout/",auth_views.LogoutView.as_view(template_name="home/logout.html"),name="logout"),

    path("add_to_cart/<int:upk>/<int:fpk>",views.add_to_cart,name="add-cart"),

    path('workout/',views.workout,name="workout"),
    
    path("cart",views.foodlistview.as_view(),name="cart"),
    path("nutrition/<int:plan>",views.nutrition,name = "nutrition"),
    path("overview/",views.nutrition_overview,name = "overview"),
    path('add_plan/',views.add_to_nutrition,name='add-plan'),
    path('edit/',views.edit,name='edit'),
    # path('change_plan/',views.change_plan,name='change-plan'),
    path('add_meal_item/<int:plan>/',views.add_meal_item,name='add-meal-item'),
    
]
urlpatterns+=staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

nutrition/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include('home.urls')),
]
 

home/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
#superuser username= akshay
#password- 123
from django.utils import timezone

from django.contrib.postgres.fields import ArrayField
from django.contrib.postgres.fields import JSONField


class  profile(models.Model):
    active_choice=[('not_active',"Not active"),('light',"Lightly Active"),('active','Active'),('very',"Very Active")]
    goal_choice=[('Gain','Gain Weight'),('maintain','Maintain Weight'),('fat_Loss','Fat loss')]

    user=models.OneToOneField(User,on_delete=models.CASCADE)
    image=models.ImageField(default='default.jfif',upload_to="profile_pics")
    email=models.EmailField(max_length=244,default="abc@gmail.com")
    height=models.IntegerField(default=0,help_text="In cms")
    weight=models.IntegerField(default=0,help_text="In kgs")
    goalweight=models.IntegerField(default=0,help_text="In kgs")
    goal=models.CharField(max_length=20,default="maintain",choices=goal_choice)
    activity_level=models.CharField(max_length=15,choices=active_choice,default='active')
    # allergies=models.Choices

    def __str__(self):  
        return f'{self.user.username} PROFILE'


class userpost(models.Model):
    post_user=models.ForeignKey(User,on_delete=models.CASCADE)
    post_title=models.CharField(max_length=220)
    post_content=models.TextField()
    date_posted=models.DateTimeField(default=timezone.now)


    def __str__(self):
        return f'{self.post_title} - {self.post_user}'

class user_foodlist(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    user_eat=models.CharField(max_length=250)
    user_calories=models.BigIntegerField(default=0)
    user_protein=models.BigIntegerField(default=0)
    user_carbs=models.BigIntegerField(default=0)
    user_fat=models.BigIntegerField(default=0)
    
    def __str__(self):
        return self.user_eat

    

    


class food(models.Model):
    food_url=models.URLField(max_length=400,default="www.google.com")
    food_name=models.CharField(max_length=200)
    carbs=models.BigIntegerField(default=0)
    servings=models.BigIntegerField(default=0)
    protein=models.BigIntegerField(default=0)
    calories=models.BigIntegerField(default=0)  
    fat=models.BigIntegerField(default=0)
    saturated=models.BigIntegerField(default=0)
    monounsaturated=models.BigIntegerField(default=0)
    trans=models.BigIntegerField(default=0)
    fiber=models.BigIntegerField(default=0)
    cholestrol=models.BigIntegerField(default=0)
    magnesium=models.BigIntegerField(default=0)
    iron=models.BigIntegerField(default=0)
    zinc=models.BigIntegerField(default=0)
    vite=models.BigIntegerField(default=0)
    vitc=models.BigIntegerField(default=0)
    vitk=models.BigIntegerField(default=0)
    vita=models.BigIntegerField(default=0)
    sugar=models.BigIntegerField(default=0)
    dietlabel= ArrayField(models.CharField(max_length=100),default=list)
    healthlabel= ArrayField(models.CharField(max_length=100),default=list)
    steps=ArrayField(models.CharField(max_length=100),default=list)
    
    def __str__(self):
        return self.food_name
    
    def get_absolute_url(self):
        return reverse("home:home-page")

class NutritionPlan(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    description = models.CharField(max_length=1000,default = '')
    plan = models.IntegerField(blank = True,null = True)
    meal = models.IntegerField(blank = True,null = True)
    meal_items= ArrayField(models.IntegerField(blank=True,null=True),default=list)

home/forms.py
from .models import food
from django.forms import ModelForm

        
from .models import food,profile
from django.forms import ModelForm
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class food_form(ModelForm):
    class Meta:
        model=food
        fields=["food_name"]



class user_register(UserCreationForm):
    email=forms.EmailField(required=True)


    class Meta:
        model=User
        fields=["username","email","password1","password2",]


class update_profile_form(forms.ModelForm):

    class Meta:
        model=profile
        fields=['image','goal','goalweight','weight','activity_level','email']

  
class update_user_form(forms.ModelForm):

    email=forms.EmailField()

    class Meta:
        model=User
        fields=['username','email'] 

home/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from fatsecret import Fatsecret
from .models import food,user_foodlist,NutritionPlan
# from .models import food
from .forms import food_form,user_register,update_profile_form,update_user_form
from django.contrib import messages

from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
import json
from django.views.generic import ListView,DetailView,CreateView
from collections import defaultdict
import requests
from urllib.parse import urlencode
from urllib.request import urlretrieve
from rest_framework.decorators import api_view
from .serializers import PlanSerializer

from rest_framework.views import APIView
from rest_framework.response import Response

# from django.Http import JsonResponse

def workout(request):
    response=requests.get("https://wger.de/api/v2/exerciseinfo/")
    response=response.json()
    exercise_muscle={}
    #----Name of exercise ---> Muscle trained.
    count=10
    while(count!=0):
        for x in response['results']:

            exercise_muscle[x['name']]=x['category']['name']
            # print(x['name'],"---->",x['category']['name'])
        
        count-=1
        response=requests.get(response['next']).json()

    #---Types of Muscle..
    response2=requests.get('https://wger.de/api/v2/muscle/')
    response2=response2.json()
    muscle_type=[]
    for x in response2["results"]:
        muscle_type.append(x["name"])
    

    
    return render(request,'home/workout.html',context={'exercise_muscle':exercise_muscle,'muscle':muscle_type})







def index(request):



    # for x in foods:
    #     print(x)
    
    if request.method=="POST":
        form=food_form(request.POST)
        if form.is_valid():
            foodname=form.cleaned_data["food_name"]
            # dietlabel=form.cleaned_data["dietlabel"]     
            mydict={'q':foodname,'app_key':'f3d813123b45b823f7c67142633c5541','app_id':'58e8a407'}
            # response2=requests.get('https://api.edamam.com/search?q=paneer-masala&app_key=f3d813123b45b823f7c67142633c5541&app_id=58e8a407&diet=low-carb&health=peanut-free&health=tree-nut-free')
            qstr=urlencode(mydict)
            urlend='https://api.edamam.com/search'
            response2=requests.get(urlend,params=mydict)
            response2j=response2.json()
            # d={}
            # print(type(response2j["hits"]))
            d=defaultdict(list)
            c=0
            for x in response2j["hits"]:
                # if c>15:
                #     break 
                # else:
                    # print(x["recipe"]["label"])
                    # print(x["recipe"]["calories"])
                    # print(x["recipe"]["totalNutrients"]["FAT"]["quantity"])
                    # print(x["recipe"]["totalNutrients"]["PROCNT"]["quantity"])
                try:
                    obj,created=food.objects.get_or_create(food_url=x["recipe"]["uri"],
                                            food_name=x["recipe"]["label"],
                                            carbs=int(x["recipe"]["totalNutrients"]["CHOCDF"]["quantity"]),
                                            servings=int(x["recipe"]["yield"]),
                                            protein=int(x["recipe"]["totalNutrients"]["PROCNT"]["quantity"]),
                                            calories=int(x["recipe"]["calories"]),
                                            fat=int(x["recipe"]["totalNutrients"]["FAT"]["quantity"]),
                                            saturated=int(x["recipe"]["totalNutrients"]["FASAT"]["quantity"]),
                                            monounsaturated=int(x["recipe"]["totalNutrients"]["FAMS"]["quantity"]),
                                            trans=int(x["recipe"]["totalNutrients"]["FATRN"]["quantity"]),
                                            fiber=int(x["recipe"]["totalNutrients"]["FIBTG"]["quantity"]),
                                            cholestrol=int(x["recipe"]["totalNutrients"]["CHOLE"]["quantity"]),
                                            magnesium=int(x["recipe"]["totalNutrients"]["MG"]["quantity"]),
                                            iron=int(x["recipe"]["totalNutrients"]["FE"]["quantity"]),
                                            zinc=int(x["recipe"]["totalNutrients"]["ZN"]["quantity"]),
                                            vite=int(x["recipe"]["totalNutrients"]["TOCPHA"]["quantity"]),
                                            vitc=int(x["recipe"]["totalNutrients"]["VITC"]["quantity"]),
                                            vitk=int(x["recipe"]["totalNutrients"]["VITK1"]["quantity"]),
                                            vita=int(x["recipe"]["totalNutrients"]["VITA_RAE"]["quantity"]),
                                            sugar=int(x["recipe"]["totalNutrients"]["SUGAR"]["quantity"]),
                                            dietlabel=x["recipe"]["dietLabels"],
                                            healthlabel=x["recipe"]["healthLabels"],
                                            steps=x["recipe"]["ingredientLines"]
                                            )
                    # print(j)
                    #j is a tuple which returns  tuple ie (object,created)
                    #created =True when new obj is created
                    #else if obj already exists  return False
                    # print(type(j))

                    if created:
                        obj.save()
                    

                    d["foodname"].append(obj.food_name)
                    d["calories"].append(obj.calories)
                    d["fat"].append(obj.fat)
                    d["protein"].append(obj.protein)
                    d["carbs"].append(obj.carbs)
                    d['dietlabel'].append(obj.dietlabel)
                    d["healthlabel"].append(obj.healthlabel)
                    d["steps"].append(obj.steps)
                    d["image"].append(x["recipe"]["image"])
                    d["servings"].append(obj.servings)
                    d["urll"].append(obj.food_url)
                    # d["foodname"].append(x["recipe"]["label"])
                    # d["calories"].append(int(x["recipe"]["calories"]))
                    # d["fat"].append(int(x["recipe"]["totalNutrients"]["FAT"]["quantity"]))
                    # d["protein"].append(int(x["recipe"]["totalNutrients"]["PROCNT"]["quantity"]))
                    # d["carbs"].append(int(x["recipe"]["totalNutrients"]["CHOCDF"]["quantity"]))
                    # d['dietlabel'].append(x["recipe"]["dietLabels"])
                    # d["healthlabel"].append(x["recipe"]["healthLabels"])
                    # d["steps"].append(x["recipe"]["ingredientLines"])
                    # d["image"].append(x["recipe"]["image"])
                    # d["servings"].append(x["recipe"]["yield"])
                    # d["urll"].append(x["recipe"]["uri"])
                    c+=1
                except KeyError:
                    print("HELLO")
             

            # print(d)
            context={'food':d,'count':range(c)}

            # fs=Fatsecret('f132e781377040bd91ef5a3cf84420c9','a920f6230b8b491ea8eb789128fce893')
            # foods = fs.foods_search(foodname)
            # # form.save()
            # # print(foods)
            # context={'foods':foods}
            return render(request,'home/fooddetails.html',context=context)
    else:
        form=food_form()
        context={'form':form}
    return render(request,"home/homepage.html",context=context)





def allinfo(request,urll):
    #urll is the url of corresponding dish 
    #that is why we used r as  a parameter

    mydict={'r':urll,'app_key':'f3d813123b45b823f7c67142633c5541','app_id':'58e8a407'}
    qstr=urlencode(mydict)
    urlend='https://api.edamam.com/search'
    response2=requests.get(urlend,params=mydict)
    response2j=response2.json()
    d=defaultdict(list)
    for x in response2j:
        # print(x["recipe"]["label"])
        # print(x["recipe"]["calories"])
        # print(x["recipe"]["totalNutrients"]["FAT"]["quantity"])
        # print(x["recipe"]["totalNutrients"]["PROCNT"]["quantity"])

        d["foodname"]=x["label"]
        d["calories"]=int(x["calories"])
        d["fat"]=int(x["totalNutrients"]["FAT"]["quantity"])
        d["saturated"]=int(x["totalNutrients"]["FASAT"]["quantity"])
        d["trans"]=int(x["totalNutrients"]["FATRN"]["quantity"])
        d["monounsaturated"]=int(x["totalNutrients"]["FAMS"]["quantity"])
        d["fiber"]=int(x["totalNutrients"]["FIBTG"]["quantity"])
        d["cholestrol"]=int(x["totalNutrients"]["CHOLE"]["quantity"])
        d["protein"]=int(x["totalNutrients"]["PROCNT"]["quantity"])
        d["carbs"]=int(x["totalNutrients"]["CHOCDF"]["quantity"])
        d["sugar"]=int(x["totalNutrients"]["SUGAR"]["quantity"])
        d["magnesium"]=int(x["totalNutrients"]["MG"]["quantity"])
        d["iron"]=int(x["totalNutrients"]["FE"]["quantity"])
        d["zinc"]=int(x["totalNutrients"]["ZN"]["quantity"])
        d["vita"]=int(x["totalNutrients"]["VITA_RAE"]["quantity"])
        d["vitc"]=int(x["totalNutrients"]["VITC"]["quantity"])
        d["vite"]=int(x["totalNutrients"]["TOCPHA"]["quantity"])
        d["vitk"]=int(x["totalNutrients"]["VITK1"]["quantity"])
        d['dietlabel']=x["dietLabels"]
        d["healthlabel"]=x["healthLabels"]
        d["steps"]=x["ingredientLines"]
        d["image"]=x["image"]
        d["servings"]=x["yield"]

    details=[d["fat"],d["protein"],d["carbs"]]
    metric=["fat","protein","carbs"]
    foodid=food.objects.get(food_url=urll).pk
    context={'food':d,'foodid':foodid,"details":details,"metric":metric}
    return render(request,"home/info.html",context=context)    





class food_search_view(CreateView):
    model=food
    fields=('food_name',)


@login_required
def profile(request):
    

home/templates/home/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>BASE</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <link href="https://code.jquery.com/ui/1.10.4/themes/ui-lightness/jquery-ui.css" rel="stylesheet">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <!-- <link rel="stylesheet" href="{% static 'styles.css' %}">  -->
  <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
  <!-- <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script> -->
  <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
    crossorigin="anonymous"></script>
  <script src="{% static 'home/js/nutrition.js'  %} "></script>
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-inverse bg-dark">
    <a class="navbar-brand" href="{% url 'admin:index' %}">ADMIN</a>

    <div class="collapse navbar-collapse">
      <ul class="navbar-nav mr-auto">

        <li class="nav-item ">
          <a class="nav-link" href="{% url 'home:home-page' %}">HOME </a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'home:workout' %}">Workout Info</a>
        </li>

      </ul>
      <div class="navbar-nav">
        {% if user.is_authenticated %}
        <a class="nav-item nav-link" href="{% url 'home:profile' %}">Profile</a>
        <a class="nav-item nav-link" href="{% url 'home:logout' %}">Logout</a>
        <a class="nav-item nav-link" href="{% url 'home:cart' %}">Cart</a>

        {% else %}

        <a class="nav-item nav-link" href="{% url 'home:login' %}">Login</a>
        <a class="nav-item nav-link" href="{% url 'home:register-user' %}">Register</a>

        {% endif %}
      </div>

    </div>
  </nav>

  <div class="container">
    <div class="col-md-12">
      {% if messages %}
      {% for message in messages %}
      <div class="alert alert-{{ message.tags}}">
        {{ message}}
      </div>
      {% endfor %}
      {% endif %}
    </div>
  </div>
  <div class="row">
    {% block content %}


    {% endblock %}
  </div>


  {% block body_block %}


  {% endblock %}

  <script>
    $(document).ready(function () {
      console.log("Inside")
      wgerInitIngredientAutocompleter()
    })
    async function add_plan() {
      var plan = prompt("Enter your plan:")
      await $.ajax({
        url: 'https://wger.de/api/v2/nutritionplan/',
        beforeSend: function (xhr) { xhr.setRequestHeader('Authorization', 'Token e28b8de959a9b816168355b374282164b41f7da8'); },
        type: 'POST',
        data: {
          'description': plan
        },
        success: function (data1) {
          console.log(data1)
          $.ajax({
            url: 'https://wger.de/api/v2/meal/',
            beforeSend: function (xhr) { xhr.setRequestHeader('Authorization', 'Token e28b8de959a9b816168355b374282164b41f7da8'); },
            type: 'POST',
            data: {
              'plan': data1.id
            },
            success: function (data2) {

              console.log("data2", data2);


              var $crf_token = $('[name="csrfmiddlewaretoken"]').attr('value');
              $.ajax({
                url: '/add_plan/',
                data: JSON.stringify({
                  'user': {{ user.id }},
                'plan': data2.plan,
                'meal': data2.id,
                'description': data1.description
                        }),
            headers: { "X-CSRFToken": $crf_token },
          contentType: "application/json",
            type: 'POST',
              success: function(out) {
                console.log(out)
                var url = "{% url 'home:nutrition' 123 %}"
                var v = out.plan
                document.location.href = url.replace('123', v)
                console.log("Successfull");

              }
        })
    }
})
                  }
              })
              
          }

    function add_meal_item(meal, plan) {
      var $crf_token = $('[name="csrfmiddlewaretoken"]').attr('value');
      // window.location.href = "https://wger.de/en/nutrition/meal/item/" + meal + "/item/add/"
      var amount = $('#id_amount').val()
      var weight_unit = $('#id_weight_unit').val()
      var ingredient = $('#id_ingredient').val()
      var name = $('#id_ingredient_searchfield').val()
      var data = {
        "meal": meal,
        "amount": amount,
        "ingredient": parseInt(ingredient),
        "weight_unit": weight_unit ? parseInt(weight_unit) : null
      }

      console.log(data);
      $.ajax({
        url: "https://wger.de/api/v2/mealitem/",
        beforeSend: function (xhr) { xhr.setRequestHeader('Authorization', 'Token e28b8de959a9b816168355b374282164b41f7da8'); },
        type: 'POST',
        data: JSON.stringify(data),
        contentType: "application/json",
        success: function (response) {
          console.log(response);
          $.ajax({
            url: '/add_meal_item/'+plan+'/',
            data: JSON.stringify({
              
              'meal_items': [
                response.id]
              
                        }),
            headers: { "X-CSRFToken": $crf_token },
      contentType: "application/json",
        type: 'POST',
          success: function(out) {
            console.log(out)
            // var url = "{% url 'home:nutrition' 123 %}"
            // var v = out.plan
            // document.location.href = url.replace('123', v)
            console.log("Successfull");

          }
    })
        }
      })
      
    }





  </script>
</body>

</html>

home/templates/home/edit.html
{% extends 'home/base.html' %}
{% load wger_extras %}


{% block title %}Edit meal item{% endblock %}


{% block header %}
<script type="text/javascript">
$(document).ready(function() {
    // Init the autocompleter
    wgerInitIngredientAutocompleter();
});
</script>
{% endblock %}




{% block content %}
<form action="{{ form_action }}"
      method="post"
      class="form-horizontal">
    {% csrf_token %}
    
    {{form.ingredient}}

    <div class="form-group {% if field.errors %}has-error{% endif %}" id="form-id_ingredient_searchfield">
        <label for="id_ingredient_searchfield" class="col-md-3 control-label">
            Ingredient name"
        </label>

        <div class="col-md-9">
            <input type="text"
                   id="id_ingredient_searchfield"
                   name="ingredient_searchfield"
                   value="{{ingredient_searchfield}}"
                   class="form-control">
            <div id="exercise_name"></div>
        </div>
    </div>
    {% render_form_field form.amount %}
    {% render_form_field form.weight_unit %}
    {% render_form_submit submit_text %}
</form>
{% endblock %}

home/templates/home/food_form.html
{% extends 'home/base.html' %}

{% block body_block %}
<div class="container">

<div class="jumbotron">

    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" class="btn btn-secondary" value="Khana Dekhiye">
    </form> 
</div>
</div>

{% endblock %}

home/templates/home/fooddetails.html
{% extends 'home/base.html' %}
{% load custom_tags %}

{% block body_block %}
      <div class="container">

      {% for i in count %}
        {% if forloop.first %}<div class="row">{% endif %}
        <div class="col-md-4" style="margin-top: 10%;">
          <div class="card" >
          <img src="{{food.image|byindex:i}}" class="card-img-top" alt="...">
          <div class="card-body" >
            <h5 class="card-title"> {{ food.foodname|byindex:i }}</h5>
            <!-- <i class="material-icons">add_circle</i> -->
          </div>
          <ul class="list-group list-group-flush">
                    <li class="list-group-item"><em><b>Servings:</b></em> {{ food.servings|byindex:i }}</li>
                    <li class="list-group-item"><em><b>Calories:</b></em> {{ food.calories|byindex:i }}kcal</li>
                    <li class="list-group-item"><em><b>Carbs:</b></em> {{ food.carbs|byindex:i }}g</li>
                    <li class="list-group-item"><em><b>Fats:</b></em> {{ food.fat|byindex:i }}g</li>
                    <li class="list-group-item"><em><b>Protein:</b></em> {{ food.protein|byindex:i }}g</li>
                    
                    <li class="list-group-item">
                      <b>Diet Labels: </b>
                      {% for x in food.dietlabel|byindex:i %}
                      <button type="button" class="btn btn-info"> {{x}} </button>
                      
                      {% endfor %}
                  </li>
                  <li class="list-group-item">
                      <b>Health labels:</b>
                      {% for x in food.healthlabel|byindex:i %}
                      <button type="button" class="btn btn-info"> {{x}} </button>
                      {% endfor %}
                  </li>
          </ul>
          
          <a href="{% url 'home:recipe' urll=food.urll|byindex:i %}" class="stretched-link">
          </a>
          <!-- Stretched link Makes the whole card Clickable  -->

        </div>
            
        </div>
        {% if forloop.counter|divisibleby:3 %}</div><div class="row">{% endif %}
        {% if forloop.last %}</div>{% endif %}
      {% endfor %}

    </div>




{% endblock %}

home/templates/home/login.html
{% extends "home/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    
    <div class="container">
        <form method="POST">
            {% csrf_token %} 
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">LOG IN!!</legend>
                {{ form|crispy}}
            </fieldset>

            <div class="form-group">
                <button class="btn btn-primary" type="submit">LOGIN</button>
            </div>

            <div class="border-top pt-3">
                <small class="text-muted" >
                    Do you need an account?
                    <a class="ml-2" href="{% url 'home:register-user' %}">Sign UP!.</a>
                </small>

            </div>
        </form>
    </div>s

{% endblock content%}   

home/templates/home/logout.html
{% extends "home/base.html" %}


{% block content %}
    
            <i>YOU HAVE BEEN LOGGED OUT!</i>    
            <div class="border-top pt-3">
                <small class="text-muted" >
                    <a href="{% url 'home:login' %}">LOG IN AGAIN</a>
                </small>

            </div>
       

{% endblock content%}

home/templates/home/nutrition_overview.html
{% extends "home/base.html" %}


{% block content %}
<div class="list-group">
    {% for plan in plans %}
            <span class="glyphicon glyphicon-chevron-right pull-right"></span>

            <h4 class="list-group-item-heading">{{plan}}</h4>
            <p class="list-group-item-text">
                {{ plan.creation_date }} –
                {{ plan.get_nutritional_values.total.energy|floatformat }} 
            </p>
        </a>
    {% empty %}
        <button onclick="add_plan()">Add new plan</button>
        </a>
    {% endfor %}
</div>
{% endblock %}

home/templates/home/profile.html
{% extends 'home/base.html' %}
{% load crispy_forms_tags %}

{% block body_block %}
    
<div class="container">
<div class="content-section">
    <div class="media">
      <img class="rounded-circle account-img" src="{{ user.profile.image.url }}">
      <div class="media-body">
        <h2 class="account-heading">{{ user.username }}</h2>
        <p class="text-secondary">{{ user.email }}</p>
      </div>
    </div>
    



      
      <form method="POST" enctype="multipart/form-data">
        {% csrf_token %} 
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">PROFILE INFO </legend>
            {{ form|crispy }}
        </fieldset>

        <div class="form-group">
            <button class="btn btn-primary" type="submit">UPDATE</button>
        </div>
    </form>


  </div>
</div>
{% endblock %}